# Generated by Django 4.2.3 on 2023-07-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='phone',
            field=models.CharField(help_text='Phone number in the format +998(__)_______', max_length=15, verbose_name='Phone'),
        ),
    ]
